project:
  type: website
  output-dir: docs

website:
  title: "Neel"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: about.qmd
    right:
      - icon: github
        href: "https://github.com/neelthakurdas"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


